In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data/Fish.csv')
df

    Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Species      159 non-null    str
 1   Weight       159 non-null    float64
 2   VerticalLen  159 non-null    float64
 3   DiagonalLen  159 non-null    float64
 4   CrossLen     159 non-null    float64
 5   Height       159 non-null    float64
 6   Width        159 non-null    float64
dtypes: float64(6), str(1)
memory usage: 8.8 KB

In [4]:
encoded_species = pd.get_dummies(df.Species)
encoded_species.head(5)

   Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0   True   False  False  False  False  False      False
1   True   False  False  False  False  False      False
2   True   False  False  False  False  False      False
3   True   False  False  False  False  False      False
4   True   False  False  False  False  False      False

In [5]:
new_df = pd.concat([df, encoded_species], axis = 1)
new_df

    Species  Weight  VerticalLen  DiagonalLen  ...   Pike  Roach  Smelt  Whitefish
0     Bream   242.0         23.2         25.4  ...  False  False  False      False
1     Bream   290.0         24.0         26.3  ...  False  False  False      False
2     Bream   340.0         23.9         26.5  ...  False  False  False      False
3     Bream   363.0         26.3         29.0  ...  False  False  False      False
4     Bream   430.0         26.5         29.0  ...  False  False  False      False
..      ...     ...          ...          ...  ...    ...    ...    ...        ...
154   Smelt    12.2         11.5         12.2  ...  False  False   True      False
155   Smelt    13.4         11.7         12.4  ...  False  False   True      False
156   Smelt    12.2         12.1         13.0  ...  False  False   True      False
157   Smelt    19.7         13.2         14.3  ...  False  False   True      False
158   Smelt    19.9         13.8         15.0  ...  False  False   True      False

[159 rows x 14 columns]

In [8]:
X = new_df[['VerticalLen',	'DiagonalLen',	'CrossLen',	'Height', 	'Width', 'Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish']]
y = new_df['Weight']

In [9]:
X = X.values
y = y.values

In [10]:
X

array([[23.2, 25.4, 30.0, ..., False, False, False],
       [24.0, 26.3, 31.2, ..., False, False, False],
       [23.9, 26.5, 31.1, ..., False, False, False],
       ...,
       [12.1, 13.0, 13.8, ..., False, True, False],
       [13.2, 14.3, 15.2, ..., False, True, False],
       [13.8, 15.0, 16.2, ..., False, True, False]],
      shape=(159, 12), dtype=object)

In [11]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ,
        200. ,  300. ,  300. ,  300. ,  430. ,  345. ,  456. ,  510. ,
        540. ,  500. ,  567. ,  770. ,  950. , 1250. , 1600. , 1550. ,
       1650. ,    6.7,    7.5,    7. ,    9.7,    9.8,    8.7,   10. ,
          9.9,    9.8,   12.2,   13.4,   12.2,   19.7,   19.9])

In [20]:
X_data = np.hstack((np.ones((X.shape[0], 1)), X))
X_data

array([[1.0, 23.2, 25.4, ..., False, False, False],
       [1.0, 24.0, 26.3, ..., False, False, False],
       [1.0, 23.9, 26.5, ..., False, False, False],
       ...,
       [1.0, 12.1, 13.0, ..., False, True, False],
       [1.0, 13.2, 14.3, ..., False, True, False],
       [1.0, 13.8, 15.0, ..., False, True, False]],
      shape=(159, 13), dtype=object)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print('X_train shape: ', X_train.shape)
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape : {y_test.shape}')

X_train shape:  (127, 13)
X_test shape: (32, 13)
y_train shape: (127,)
y_test shape : (32,)

In [22]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y - y.mean()) ** 2)
    r2 = 1 - (rss / tss)
    return r2

In [25]:
class LinearRegression:
    def __init__(self, X_data, y_target, learning_rate = 0.00001, num_epochs = 10000):
        self.X_data = X_data
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.num_samples = self.X_data.shape[0]

        # Initial Coefficient
        self.theta = np.random.randn(self.X_data.shape[1]) # [b w]
        self.losses = []
    def compute_loss(self, y_pred, y_target):
        loss = (y_pred - y_target) ** 2
        loss = np.mean(loss)
        return loss
    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred
    def fit(self):
        for epoch in range(self.num_epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # compute gradient
            k = 2 * (y_pred - self.y_target)
            gradients = self.X_data.T.dot(k) / self.num_samples

            # update weights
            self.theta = self.theta - self.learning_rate * gradients

            print(f'Epoch: {epoch} - Loss : {loss}')
        return {
            'loss': sum(self.losses) / len(self.losses),
            'weight': self.theta
        }

In [26]:
linear_model = LinearRegression(X_train, y_train, learning_rate = 0.0001, num_epochs = 100)
linear_model.fit()

Epoch: 0 - Loss : 346783.32662979414
Epoch: 1 - Loss : 101057.65998393751
Epoch: 2 - Loss : 56973.29189398247
Epoch: 3 - Loss : 49061.14267951918
Epoch: 4 - Loss : 47637.896035834754
Epoch: 5 - Loss : 47378.69445393143
Epoch: 6 - Loss : 47328.3175662048
Epoch: 7 - Loss : 47315.409407576335
Epoch: 8 - Loss : 47309.23058642346
Epoch: 9 - Loss : 47304.26676377258
Epoch: 10 - Loss : 47299.528695254114
Epoch: 11 - Loss : 47294.83888838735
Epoch: 12 - Loss : 47290.165470113425
Epoch: 13 - Loss : 47285.502690023575
Epoch: 14 - Loss : 47280.849483964215
Epoch: 15 - Loss : 47276.20562858473
Epoch: 16 - Loss : 47271.571051505794
Epoch: 17 - Loss : 47266.94570757017
Epoch: 18 - Loss : 47262.32955664347
Epoch: 19 - Loss : 47257.72255963056
Epoch: 20 - Loss : 47253.12467776092
Epoch: 21 - Loss : 47248.53587245957
Epoch: 22 - Loss : 47243.95610532332
Epoch: 23 - Loss : 47239.38533811595
Epoch: 24 - Loss : 47234.82353276698
Epoch: 25 - Loss : 47230.27065137042
Epoch: 26 - Loss : 47225.72665618432
Epoch: 27 - Loss : 47221.19150962998
Epoch: 28 - Loss : 47216.66517429123
Epoch: 29 - Loss : 47212.14761291372
Epoch: 30 - Loss : 47207.63878840436
Epoch: 31 - Loss : 47203.138663830214
Epoch: 32 - Loss : 47198.64720241837
Epoch: 33 - Loss : 47194.16436755491
Epoch: 34 - Loss : 47189.69012278414
Epoch: 35 - Loss : 47185.2244318082
Epoch: 36 - Loss : 47180.76725848617
Epoch: 37 - Loss : 47176.31856683336
Epoch: 38 - Loss : 47171.87832102094
Epoch: 39 - Loss : 47167.44648537481
Epoch: 40 - Loss : 47163.02302437531
Epoch: 41 - Loss : 47158.6079026563
Epoch: 42 - Loss : 47154.201085004825
Epoch: 43 - Loss : 47149.80253635995
Epoch: 44 - Loss : 47145.412221812585
Epoch: 45 - Loss : 47141.03010660451
Epoch: 46 - Loss : 47136.656156127894
Epoch: 47 - Loss : 47132.290335924576
Epoch: 48 - Loss : 47127.93261168548
Epoch: 49 - Loss : 47123.58294924984
Epoch: 50 - Loss : 47119.24131460469
Epoch: 51 - Loss : 47114.907673884125
Epoch: 52 - Loss : 47110.58199336878
Epoch: 53 - Loss : 47106.26423948508
Epoch: 54 - Loss : 47101.95437880464
Epoch: 55 - Loss : 47097.65237804377
Epoch: 56 - Loss : 47093.358204062555
Epoch: 57 - Loss : 47089.07182386459
Epoch: 58 - Loss : 47084.79320459609
Epoch: 59 - Loss : 47080.5223135453
Epoch: 60 - Loss : 47076.259118141985
Epoch: 61 - Loss : 47072.00358595697
Epoch: 62 - Loss : 47067.755684701064
Epoch: 63 - Loss : 47063.515382224774
Epoch: 64 - Loss : 47059.28264651784
Epoch: 65 - Loss : 47055.05744570819
Epoch: 66 - Loss : 47050.83974806183
Epoch: 67 - Loss : 47046.629521981806
Epoch: 68 - Loss : 47042.42673600801
Epoch: 69 - Loss : 47038.231358816265
Epoch: 70 - Loss : 47034.043359217925
Epoch: 71 - Loss : 47029.862706159176
Epoch: 72 - Loss : 47025.68936872056
Epoch: 73 - Loss : 47021.523316116356
Epoch: 74 - Loss : 47017.364517693946
Epoch: 75 - Loss : 47013.21294293325
Epoch: 76 - Loss : 47009.068561446256
Epoch: 77 - Loss : 47004.93134297643
Epoch: 78 - Loss : 47000.80125739787
Epoch: 79 - Loss : 46996.67827471518
Epoch: 80 - Loss : 46992.56236506261
Epoch: 81 - Loss : 46988.45349870352
Epoch: 82 - Loss : 46984.35164602997
Epoch: 83 - Loss : 46980.25677756204
Epoch: 84 - Loss : 46976.16886394727
Epoch: 85 - Loss : 46972.087875960155
Epoch: 86 - Loss : 46968.013784501534
Epoch: 87 - Loss : 46963.94656059825
Epoch: 88 - Loss : 46959.88617540222
Epoch: 89 - Loss : 46955.832600190384
Epoch: 90 - Loss : 46951.78580636368
Epoch: 91 - Loss : 46947.745765446794
Epoch: 92 - Loss : 46943.712449087594
Epoch: 93 - Loss : 46939.68582905655
Epoch: 94 - Loss : 46935.6658772462
Epoch: 95 - Loss : 46931.652565670614
Epoch: 96 - Loss : 46927.64586646496
Epoch: 97 - Loss : 46923.64575188482
Epoch: 98 - Loss : 46919.65219430586
Epoch: 99 - Loss : 46915.665166223145

{'loss': np.float64(50773.70117821253),
 'weight': array([-0.6460620572366462, 4.590129555189741, 4.104947712237566,
        6.1501943007679785, 2.1507683996025664, 0.48152148236460224,
        -0.3086033451570806, 0.5116143814539567, -1.3517879864654843,
        0.4425440460327906, 0.7542371677198665, -1.56091427399217,
        0.011305551668067354], dtype=object)}

In [27]:
preds = linear_model.predict(X_train)
r2score(preds, y_train)

np.float64(0.6198293170720954)

In [28]:
preds =  linear_model.predict(X_test)
r2score(preds, y_test)

np.float64(0.655673805162095)

In [35]:
# Simple Approach
# from (a + b) ^ 2 = a ^ 2 + b ^ 2 + a + b + 1

def create_polynomial_features(X, degree = 2):
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [36]:
X_new = np.array([
    [1, 2],
    [3, 4]
])
X_new

array([[1, 2],
       [3, 4]])

In [37]:
create_polynomial_features(X_new, degree = 2)

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

In [38]:
create_polynomial_features(X_new, degree = 3)

array([[ 1,  1,  1,  2,  4,  8],
       [ 3,  9, 27,  4, 16, 64]])

In [39]:
X_poly = create_polynomial_features(X, degree = 2)
X_poly

array([[23.2, 538.24, 25.4, ..., 0, False, 0],
       [24.0, 576.0, 26.3, ..., 0, False, 0],
       [23.9, 571.2099999999999, 26.5, ..., 0, False, 0],
       ...,
       [12.1, 146.41, 13.0, ..., 1, False, 0],
       [13.2, 174.23999999999998, 14.3, ..., 1, False, 0],
       [13.8, 190.44000000000003, 15.0, ..., 1, False, 0]],
      shape=(159, 24), dtype=object)

In [40]:
X_poly.shape

(159, 24)

In [42]:
X_data = np.hstack((np.ones((X_poly.shape[0], 1)), X_poly))
X_data

array([[1.0, 23.2, 538.24, ..., 0, False, 0],
       [1.0, 24.0, 576.0, ..., 0, False, 0],
       [1.0, 23.9, 571.2099999999999, ..., 0, False, 0],
       ...,
       [1.0, 12.1, 146.41, ..., 1, False, 0],
       [1.0, 13.2, 174.23999999999998, ..., 1, False, 0],
       [1.0, 13.8, 190.44000000000003, ..., 1, False, 0]],
      shape=(159, 25), dtype=object)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print(f'X_train shape : {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape : (127, 25)
X_test shape: (32, 25)
y_train shape: (127,)
y_test shape: (32,)

In [44]:
poly_model = LinearRegression(X_train, y_train, learning_rate = 0.0000001, num_epochs = 100)
poly_model.fit()

Epoch: 0 - Loss : 8809706.517471481
Epoch: 1 - Loss : 349438.79383395007
Epoch: 2 - Loss : 55046.595963345666
Epoch: 3 - Loss : 44718.76254117199
Epoch: 4 - Loss : 44272.96350970635
Epoch: 5 - Loss : 44171.29431655301
Epoch: 6 - Loss : 44081.960954144066
Epoch: 7 - Loss : 43993.419777474846
Epoch: 8 - Loss : 43905.26760726303
Epoch: 9 - Loss : 43817.48881164418
Epoch: 10 - Loss : 43730.081247422066
Epoch: 11 - Loss : 43643.04324776082
Epoch: 12 - Loss : 43556.37316949772
Epoch: 13 - Loss : 43470.06937736406
Epoch: 14 - Loss : 43384.13024340472
Epoch: 15 - Loss : 43298.55414692632
Epoch: 16 - Loss : 43213.339474464614
Epoch: 17 - Loss : 43128.48461975168
Epoch: 18 - Loss : 43043.98798368435
Epoch: 19 - Loss : 42959.847974291835
Epoch: 20 - Loss : 42876.06300670406
Epoch: 21 - Loss : 42792.631503119956
Epoch: 22 - Loss : 42709.551892776006
Epoch: 23 - Loss : 42626.82261191479
Epoch: 24 - Loss : 42544.44210375358
Epoch: 25 - Loss : 42462.4088184535
Epoch: 26 - Loss : 42380.72121308832
Epoch: 27 - Loss : 42299.37775161376
Epoch: 28 - Loss : 42218.37690483672
Epoch: 29 - Loss : 42137.71715038468
Epoch: 30 - Loss : 42057.39697267531
Epoch: 31 - Loss : 41977.41486288624
Epoch: 32 - Loss : 41897.76931892469
Epoch: 33 - Loss : 41818.45884539784
Epoch: 34 - Loss : 41739.4819535824
Epoch: 35 - Loss : 41660.83716139534
Epoch: 36 - Loss : 41582.52299336397
Epoch: 37 - Loss : 41504.53798059656
Epoch: 38 - Loss : 41426.88066075309
Epoch: 39 - Loss : 41349.54957801571
Epoch: 40 - Loss : 41272.543283059815
Epoch: 41 - Loss : 41195.8603330253
Epoch: 42 - Loss : 41119.49929148729
Epoch: 43 - Loss : 41043.458728427686
Epoch: 44 - Loss : 40967.73722020668
Epoch: 45 - Loss : 40892.33334953392
Epoch: 46 - Loss : 40817.245705440684
Epoch: 47 - Loss : 40742.47288325112
Epoch: 48 - Loss : 40668.013484554634
Epoch: 49 - Loss : 40593.866117177786
Epoch: 50 - Loss : 40520.02939515632
Epoch: 51 - Loss : 40446.50193870765
Epoch: 52 - Loss : 40373.28237420326
Epoch: 53 - Loss : 40300.36933414103
Epoch: 54 - Loss : 40227.761457118286
Epoch: 55 - Loss : 40155.457387804236
Epoch: 56 - Loss : 40083.455776913055
Epoch: 57 - Loss : 40011.755281176826
Epoch: 58 - Loss : 39940.354563318775
Epoch: 59 - Loss : 39869.25229202656
Epoch: 60 - Loss : 39798.447141925615
Epoch: 61 - Loss : 39727.937793552504
Epoch: 62 - Loss : 39657.722933328805
Epoch: 63 - Loss : 39587.801253534824
Epoch: 64 - Loss : 39518.17145228321
Epoch: 65 - Loss : 39448.832233493195
Epoch: 66 - Loss : 39379.782306864625
Epoch: 67 - Loss : 39311.020387852055
Epoch: 68 - Loss : 39242.54519763921
Epoch: 69 - Loss : 39174.3554631134
Epoch: 70 - Loss : 39106.449916839934
Epoch: 71 - Loss : 39038.827297037045
Epoch: 72 - Loss : 38971.48634755037
Epoch: 73 - Loss : 38904.425817828174
Epoch: 74 - Loss : 38837.64446289605
Epoch: 75 - Loss : 38771.1410433322
Epoch: 76 - Loss : 38704.91432524261
Epoch: 77 - Loss : 38638.96308023637
Epoch: 78 - Loss : 38573.28608540136
Epoch: 79 - Loss : 38507.88212327923
Epoch: 80 - Loss : 38442.74998184186
Epoch: 81 - Loss : 38377.88845446638
Epoch: 82 - Loss : 38313.296339911496
Epoch: 83 - Loss : 38248.97244229347
Epoch: 84 - Loss : 38184.91557106194
Epoch: 85 - Loss : 38121.124540976445
Epoch: 86 - Loss : 38057.5981720826
Epoch: 87 - Loss : 37994.33528968829
Epoch: 88 - Loss : 37931.33472434069
Epoch: 89 - Loss : 37868.5953118025
Epoch: 90 - Loss : 37806.11589302872
Epoch: 91 - Loss : 37743.89531414356
Epoch: 92 - Loss : 37681.93242641748
Epoch: 93 - Loss : 37620.22608624399
Epoch: 94 - Loss : 37558.77515511692
Epoch: 95 - Loss : 37497.57849960779
Epoch: 96 - Loss : 37436.634991342886
Epoch: 97 - Loss : 37375.94350698098
Epoch: 98 - Loss : 37315.50292819062
Epoch: 99 - Loss : 37255.31214162801

{'loss': np.float64(131496.19554186668),
 'weight': array([-0.5914197706948657, 0.4240540275205103, 1.209923384250954,
        0.019061645631641953, -1.4478452454981212, 1.3714559573057121,
        0.769957856943973, 0.3635291418509782, -1.1783305593922493,
        0.6291342182956616, -0.36716720186994484, 0.3221717584420155,
        0.20163628701095881, 0.6720171663218579, 0.001129235374928195,
        0.515523658825304, 0.365241562097453, -1.0766550197183535,
        -0.1661698671311507, 0.33078320264318034, -0.6028210986307332,
        -0.3114973620558539, 0.6146463991856891, -1.1737622598340391,
        -0.024942956942605222], dtype=object)}

In [45]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

np.float64(0.698569997264231)

In [46]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

np.float64(0.7374619871767933)

In [47]:
from sklearn.preprocessing import PolynomialFeatures

In [48]:
poly_features = PolynomialFeatures(degree = 2, interaction_only = True)
X_data = poly_features.fit_transform(X)
X_data

array([[ 1. , 23.2, 25.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 24. , 26.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 23.9, 26.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 12.1, 13. , ...,  0. ,  0. ,  0. ],
       [ 1. , 13.2, 14.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.8, 15. , ...,  0. ,  0. ,  0. ]], shape=(159, 79))

In [ ]:
X_data.shape

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print(f'X_train shape : {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape : (127, 79)
X_test shape: (32, 79)
y_train shape: (127,)
y_test shape: (32,)