In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [55]:
df = pd.read_csv('data/Fish.csv')
df

    Species  Weight  VerticalLen  DiagonalLen  CrossLen   Height   Width
0     Bream   242.0         23.2         25.4      30.0  11.5200  4.0200
1     Bream   290.0         24.0         26.3      31.2  12.4800  4.3056
2     Bream   340.0         23.9         26.5      31.1  12.3778  4.6961
3     Bream   363.0         26.3         29.0      33.5  12.7300  4.4555
4     Bream   430.0         26.5         29.0      34.0  12.4440  5.1340
..      ...     ...          ...          ...       ...      ...     ...
154   Smelt    12.2         11.5         12.2      13.4   2.0904  1.3936
155   Smelt    13.4         11.7         12.4      13.5   2.4300  1.2690
156   Smelt    12.2         12.1         13.0      13.8   2.2770  1.2558
157   Smelt    19.7         13.2         14.3      15.2   2.8728  2.0672
158   Smelt    19.9         13.8         15.0      16.2   2.9322  1.8792

[159 rows x 7 columns]

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Species      159 non-null    str
 1   Weight       159 non-null    float64
 2   VerticalLen  159 non-null    float64
 3   DiagonalLen  159 non-null    float64
 4   CrossLen     159 non-null    float64
 5   Height       159 non-null    float64
 6   Width        159 non-null    float64
dtypes: float64(6), str(1)
memory usage: 8.8 KB

In [57]:
encoded_species = pd.get_dummies(df.Species)
encoded_species.head(5)

   Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0   True   False  False  False  False  False      False
1   True   False  False  False  False  False      False
2   True   False  False  False  False  False      False
3   True   False  False  False  False  False      False
4   True   False  False  False  False  False      False

In [58]:
new_df = pd.concat([df, encoded_species], axis = 1)
new_df

    Species  Weight  VerticalLen  DiagonalLen  ...   Pike  Roach  Smelt  Whitefish
0     Bream   242.0         23.2         25.4  ...  False  False  False      False
1     Bream   290.0         24.0         26.3  ...  False  False  False      False
2     Bream   340.0         23.9         26.5  ...  False  False  False      False
3     Bream   363.0         26.3         29.0  ...  False  False  False      False
4     Bream   430.0         26.5         29.0  ...  False  False  False      False
..      ...     ...          ...          ...  ...    ...    ...    ...        ...
154   Smelt    12.2         11.5         12.2  ...  False  False   True      False
155   Smelt    13.4         11.7         12.4  ...  False  False   True      False
156   Smelt    12.2         12.1         13.0  ...  False  False   True      False
157   Smelt    19.7         13.2         14.3  ...  False  False   True      False
158   Smelt    19.9         13.8         15.0  ...  False  False   True      False

[159 rows x 14 columns]

In [59]:
X = new_df[['VerticalLen',	'DiagonalLen',	'CrossLen',	'Height', 	'Width', 'Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish']]
y = new_df['Weight']

In [60]:
X = X.values
y = y.values

In [61]:
X

array([[23.2, 25.4, 30.0, ..., False, False, False],
       [24.0, 26.3, 31.2, ..., False, False, False],
       [23.9, 26.5, 31.1, ..., False, False, False],
       ...,
       [12.1, 13.0, 13.8, ..., False, True, False],
       [13.2, 14.3, 15.2, ..., False, True, False],
       [13.8, 15.0, 16.2, ..., False, True, False]],
      shape=(159, 12), dtype=object)

In [62]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ,
        200. ,  300. ,  300. ,  300. ,  430. ,  345. ,  456. ,  510. ,
        540. ,  500. ,  567. ,  770. ,  950. , 1250. , 1600. , 1550. ,
       1650. ,    6.7,    7.5,    7. ,    9.7,    9.8,    8.7,   10. ,
          9.9,    9.8,   12.2,   13.4,   12.2,   19.7,   19.9])

In [63]:
X_data = np.hstack((np.ones((X.shape[0], 1)), X))
X_data

array([[1.0, 23.2, 25.4, ..., False, False, False],
       [1.0, 24.0, 26.3, ..., False, False, False],
       [1.0, 23.9, 26.5, ..., False, False, False],
       ...,
       [1.0, 12.1, 13.0, ..., False, True, False],
       [1.0, 13.2, 14.3, ..., False, True, False],
       [1.0, 13.8, 15.0, ..., False, True, False]],
      shape=(159, 13), dtype=object)

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print('X_train shape: ', X_train.shape)
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape : {y_test.shape}')

X_train shape:  (127, 13)
X_test shape: (32, 13)
y_train shape: (127,)
y_test shape : (32,)

In [65]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y - y.mean()) ** 2)
    r2 = 1 - (rss / tss)
    return r2

In [66]:
class LinearRegression:
    def __init__(self, X_data, y_target, learning_rate = 0.00001, num_epochs = 10000):
        self.X_data = X_data
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.num_samples = self.X_data.shape[0]

        # Initial Coefficient
        self.theta = np.random.randn(self.X_data.shape[1]) # [b w]
        self.losses = []
    def compute_loss(self, y_pred, y_target):
        loss = (y_pred - y_target) ** 2
        loss = np.mean(loss)
        return loss
    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred
    def fit(self):
        for epoch in range(self.num_epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # compute gradient
            k = 2 * (y_pred - self.y_target)
            gradients = self.X_data.T.dot(k) / self.num_samples

            # update weights
            self.theta = self.theta - self.learning_rate * gradients

            print(f'Epoch: {epoch} - Loss : {loss}')
        return {
            'loss': sum(self.losses) / len(self.losses),
            'weight': self.theta
        }

In [67]:
linear_model = LinearRegression(X_train, y_train, learning_rate = 0.0001, num_epochs = 100)
linear_model.fit()

Epoch: 0 - Loss : 339778.43495059374
Epoch: 1 - Loss : 99711.26744267897
Epoch: 2 - Loss : 56641.867245984045
Epoch: 3 - Loss : 48911.68845833384
Epoch: 4 - Loss : 47520.982237652155
Epoch: 5 - Loss : 47267.515488330646
Epoch: 6 - Loss : 47218.065299315764
Epoch: 7 - Loss : 47205.22180294126
Epoch: 8 - Loss : 47198.95349153747
Epoch: 9 - Loss : 47193.873010541036
Epoch: 10 - Loss : 47189.0138930713
Epoch: 11 - Loss : 47184.20273058075
Epoch: 12 - Loss : 47179.408380536224
Epoch: 13 - Loss : 47174.62522149977
Epoch: 14 - Loss : 47169.85221038509
Epoch: 15 - Loss : 47165.089125561346
Epoch: 16 - Loss : 47160.33589290704
Epoch: 17 - Loss : 47155.59246491072
Epoch: 18 - Loss : 47150.85879898262
Epoch: 19 - Loss : 47146.134853563126
Epoch: 20 - Loss : 47141.420587424174
Epoch: 21 - Loss : 47136.715959543326
Epoch: 22 - Loss : 47132.02092908037
Epoch: 23 - Loss : 47127.335455372624
Epoch: 24 - Loss : 47122.65949793351
Epoch: 25 - Loss : 47117.993016451604
Epoch: 26 - Loss : 47113.33597078984
Epoch: 27 - Loss : 47108.6883209847
Epoch: 28 - Loss : 47104.05002724558
Epoch: 29 - Loss : 47099.42104995398
Epoch: 30 - Loss : 47094.80134966283
Epoch: 31 - Loss : 47090.190887095545
Epoch: 32 - Loss : 47085.589623145555
Epoch: 33 - Loss : 47080.99751887537
Epoch: 34 - Loss : 47076.41453551594
Epoch: 35 - Loss : 47071.84063446593
Epoch: 36 - Loss : 47067.27577729097
Epoch: 37 - Loss : 47062.71992572284
Epoch: 38 - Loss : 47058.17304165898
Epoch: 39 - Loss : 47053.63508716154
Epoch: 40 - Loss : 47049.10602445688
Epoch: 41 - Loss : 47044.585815934515
Epoch: 42 - Loss : 47040.07442414689
Epoch: 43 - Loss : 47035.571811808295
Epoch: 44 - Loss : 47031.07794179431
Epoch: 45 - Loss : 47026.59277714108
Epoch: 46 - Loss : 47022.11628104465
Epoch: 47 - Loss : 47017.648416860226
Epoch: 48 - Loss : 47013.1891481016
Epoch: 49 - Loss : 47008.73843844022
Epoch: 50 - Loss : 47004.29625170486
Epoch: 51 - Loss : 46999.862551880484
Epoch: 52 - Loss : 46995.43730310814
Epoch: 53 - Loss : 46991.02046968373
Epoch: 54 - Loss : 46986.61201605768
Epoch: 55 - Loss : 46982.2119068342
Epoch: 56 - Loss : 46977.82010677052
Epoch: 57 - Loss : 46973.436580776346
Epoch: 58 - Loss : 46969.06129391321
Epoch: 59 - Loss : 46964.69421139365
Epoch: 60 - Loss : 46960.3352985807
Epoch: 61 - Loss : 46955.98452098731
Epoch: 62 - Loss : 46951.64184427538
Epoch: 63 - Loss : 46947.30723425554
Epoch: 64 - Loss : 46942.98065688623
Epoch: 65 - Loss : 46938.66207827301
Epoch: 66 - Loss : 46934.351464668165
Epoch: 67 - Loss : 46930.048782469916
Epoch: 68 - Loss : 46925.753998221815
Epoch: 69 - Loss : 46921.46707861206
Epoch: 70 - Loss : 46917.18799047306
Epoch: 71 - Loss : 46912.91670078044
Epoch: 72 - Loss : 46908.65317665294
Epoch: 73 - Loss : 46904.3973853513
Epoch: 74 - Loss : 46900.14929427795
Epoch: 75 - Loss : 46895.908870976324
Epoch: 76 - Loss : 46891.676083130165
Epoch: 77 - Loss : 46887.45089856304
Epoch: 78 - Loss : 46883.233285237635
Epoch: 79 - Loss : 46879.023211255255
Epoch: 80 - Loss : 46874.82064485508
Epoch: 81 - Loss : 46870.6255544137
Epoch: 82 - Loss : 46866.43790844454
Epoch: 83 - Loss : 46862.257675597146
Epoch: 84 - Loss : 46858.084824656544
Epoch: 85 - Loss : 46853.919324543
Epoch: 86 - Loss : 46849.76114431102
Epoch: 87 - Loss : 46845.610253148974
Epoch: 88 - Loss : 46841.466620378495
Epoch: 89 - Loss : 46837.330215453956
Epoch: 90 - Loss : 46833.20100796178
Epoch: 91 - Loss : 46829.078967619906
Epoch: 92 - Loss : 46824.96406427732
Epoch: 93 - Loss : 46820.85626791329
Epoch: 94 - Loss : 46816.755548637055
Epoch: 95 - Loss : 46812.66187668698
Epoch: 96 - Loss : 46808.575222430336
Epoch: 97 - Loss : 46804.49555636225
Epoch: 98 - Loss : 46800.42284910583
Epoch: 99 - Loss : 46796.357071410894

{'loss': np.float64(50574.982284192694),
 'weight': array([-0.9627222156173274, 5.9174568909272995, 4.664950425797391,
        4.344501445690688, 2.616727920578576, 0.6127723134317354,
        0.9077569294141138, -1.2766696621402596, 0.30503779156779176,
        1.344008033702437, 1.374469662208825, -0.6104845718125663,
        3.241157496283346], dtype=object)}

In [68]:
preds = linear_model.predict(X_train)
r2score(preds, y_train)

np.float64(0.6207968207354777)

In [69]:
preds =  linear_model.predict(X_test)
r2score(preds, y_test)

np.float64(0.6566213012784528)

In [70]:
# Simple Approach
# from (a + b) ^ 2 = a ^ 2 + b ^ 2 + a + b + 1

def create_polynomial_features(X, degree = 2):
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [71]:
X_new = np.array([
    [1, 2],
    [3, 4]
])
X_new

array([[1, 2],
       [3, 4]])

In [72]:
create_polynomial_features(X_new, degree = 2)

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

In [73]:
create_polynomial_features(X_new, degree = 3)

array([[ 1,  1,  1,  2,  4,  8],
       [ 3,  9, 27,  4, 16, 64]])

In [74]:
X_poly = create_polynomial_features(X, degree = 2)
X_poly

array([[23.2, 538.24, 25.4, ..., 0, False, 0],
       [24.0, 576.0, 26.3, ..., 0, False, 0],
       [23.9, 571.2099999999999, 26.5, ..., 0, False, 0],
       ...,
       [12.1, 146.41, 13.0, ..., 1, False, 0],
       [13.2, 174.23999999999998, 14.3, ..., 1, False, 0],
       [13.8, 190.44000000000003, 15.0, ..., 1, False, 0]],
      shape=(159, 24), dtype=object)

In [75]:
X_poly.shape

(159, 24)

In [76]:
X_data = np.hstack((np.ones((X_poly.shape[0], 1)), X_poly))
X_data

array([[1.0, 23.2, 538.24, ..., 0, False, 0],
       [1.0, 24.0, 576.0, ..., 0, False, 0],
       [1.0, 23.9, 571.2099999999999, ..., 0, False, 0],
       ...,
       [1.0, 12.1, 146.41, ..., 1, False, 0],
       [1.0, 13.2, 174.23999999999998, ..., 1, False, 0],
       [1.0, 13.8, 190.44000000000003, ..., 1, False, 0]],
      shape=(159, 25), dtype=object)

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print(f'X_train shape : {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape : (127, 25)
X_test shape: (32, 25)
y_train shape: (127,)
y_test shape: (32,)

In [78]:
poly_model = LinearRegression(X_train, y_train, learning_rate = 0.0000001, num_epochs = 100)
poly_model.fit()

Epoch: 0 - Loss : 20375234.001530163
Epoch: 1 - Loss : 736315.4156232788
Epoch: 2 - Loss : 53136.24235266871
Epoch: 3 - Loss : 29364.999182127904
Epoch: 4 - Loss : 28532.394388734396
Epoch: 5 - Loss : 28497.7513178035
Epoch: 6 - Loss : 28490.8685320626
Epoch: 7 - Loss : 28484.953251783307
Epoch: 8 - Loss : 28479.073443267476
Epoch: 9 - Loss : 28473.19668325261
Epoch: 10 - Loss : 28467.321842970694
Epoch: 11 - Loss : 28461.448882287877
Epoch: 12 - Loss : 28455.57779894184
Epoch: 13 - Loss : 28449.70859198906
Epoch: 14 - Loss : 28443.84126053341
Epoch: 15 - Loss : 28437.975803681962
Epoch: 16 - Loss : 28432.1122205432
Epoch: 17 - Loss : 28426.250510227135
Epoch: 18 - Loss : 28420.390671845358
Epoch: 19 - Loss : 28414.532704510875
Epoch: 20 - Loss : 28408.67660733816
Epoch: 21 - Loss : 28402.822379443216
Epoch: 22 - Loss : 28396.970019943496
Epoch: 23 - Loss : 28391.11952795789
Epoch: 24 - Loss : 28385.270902606804
Epoch: 25 - Loss : 28379.424143011995
Epoch: 26 - Loss : 28373.579248296828
Epoch: 27 - Loss : 28367.73621758591
Epoch: 28 - Loss : 28361.89505000544
Epoch: 29 - Loss : 28356.05574468301
Epoch: 30 - Loss : 28350.21830074758
Epoch: 31 - Loss : 28344.382717329612
Epoch: 32 - Loss : 28338.548993560853
Epoch: 33 - Loss : 28332.717128574644
Epoch: 34 - Loss : 28326.887121505577
Epoch: 35 - Loss : 28321.058971489685
Epoch: 36 - Loss : 28315.232677664426
Epoch: 37 - Loss : 28309.408239168602
Epoch: 38 - Loss : 28303.58565514239
Epoch: 39 - Loss : 28297.764924727395
Epoch: 40 - Loss : 28291.946047066554
Epoch: 41 - Loss : 28286.129021304165
Epoch: 42 - Loss : 28280.313846585927
Epoch: 43 - Loss : 28274.50052205885
Epoch: 44 - Loss : 28268.689046871277
Epoch: 45 - Loss : 28262.879420172932
Epoch: 46 - Loss : 28257.07164111493
Epoch: 47 - Loss : 28251.265708849587
Epoch: 48 - Loss : 28245.461622530667
Epoch: 49 - Loss : 28239.659381313184
Epoch: 50 - Loss : 28233.85898435351
Epoch: 51 - Loss : 28228.060430809328
Epoch: 52 - Loss : 28222.263719839582
Epoch: 53 - Loss : 28216.468850604622
Epoch: 54 - Loss : 28210.675822265985
Epoch: 55 - Loss : 28204.88463398657
Epoch: 56 - Loss : 28199.095284930507
Epoch: 57 - Loss : 28193.30777426332
Epoch: 58 - Loss : 28187.522101151662
Epoch: 59 - Loss : 28181.738264763568
Epoch: 60 - Loss : 28175.95626426828
Epoch: 61 - Loss : 28170.17609883641
Epoch: 62 - Loss : 28164.397767639683
Epoch: 63 - Loss : 28158.62126985116
Epoch: 64 - Loss : 28152.846604645143
Epoch: 65 - Loss : 28147.073771197196
Epoch: 66 - Loss : 28141.302768684065
Epoch: 67 - Loss : 28135.53359628381
Epoch: 68 - Loss : 28129.766253175658
Epoch: 69 - Loss : 28124.000738540108
Epoch: 70 - Loss : 28118.23705155883
Epoch: 71 - Loss : 28112.47519141477
Epoch: 72 - Loss : 28106.715157292023
Epoch: 73 - Loss : 28100.95694837595
Epoch: 74 - Loss : 28095.200563853083
Epoch: 75 - Loss : 28089.446002911136
Epoch: 76 - Loss : 28083.69326473909
Epoch: 77 - Loss : 28077.942348527064
Epoch: 78 - Loss : 28072.193253466306
Epoch: 79 - Loss : 28066.445978749314
Epoch: 80 - Loss : 28060.700523569805
Epoch: 81 - Loss : 28054.95688712257
Epoch: 82 - Loss : 28049.215068603644
Epoch: 83 - Loss : 28043.475067210155
Epoch: 84 - Loss : 28037.73688214045
Epoch: 85 - Loss : 28032.000512594
Epoch: 86 - Loss : 28026.265957771466
Epoch: 87 - Loss : 28020.53321687455
Epoch: 88 - Loss : 28014.802289106232
Epoch: 89 - Loss : 28009.073173670553
Epoch: 90 - Loss : 28003.34586977264
Epoch: 91 - Loss : 27997.620376618896
Epoch: 92 - Loss : 27991.896693416707
Epoch: 93 - Loss : 27986.174819374635
Epoch: 94 - Loss : 27980.45475370238
Epoch: 95 - Loss : 27974.73649561071
Epoch: 96 - Loss : 27969.02004431149
Epoch: 97 - Loss : 27963.305399017765
Epoch: 98 - Loss : 27957.592558943594
Epoch: 99 - Loss : 27951.881523304208

{'loss': np.float64(239037.64972295042),
 'weight': array([-0.7719711489643645, 1.6672705730637587, -0.8119215627014923,
        0.4288976532496955, -0.6077009653390539, 0.552377999685458,
        1.4958380926094101, 0.07413132886679948, -1.0101395182921173,
        -0.630440150228875, 0.3356040654601684, -1.0359693271828654,
        -0.4986367208200849, -0.9695685708600557, 0.475154424066765,
        0.3170686220362615, -0.6118216514296254, -1.1710470371809771,
        1.5005786123229032, 0.4065060939678615, 0.06392426266900526,
        -0.9806223764969064, 1.822993332765796, -0.5692411899985733,
        0.8975375251804578], dtype=object)}

In [79]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

np.float64(0.7735251784990327)

In [80]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

np.float64(0.7808763718977118)

In [81]:
from sklearn.preprocessing import PolynomialFeatures

In [82]:
poly_features = PolynomialFeatures(degree = 2, interaction_only = True)
X_data = poly_features.fit_transform(X)
X_data

array([[ 1. , 23.2, 25.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 24. , 26.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 23.9, 26.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 12.1, 13. , ...,  0. ,  0. ,  0. ],
       [ 1. , 13.2, 14.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.8, 15. , ...,  0. ,  0. ,  0. ]], shape=(159, 79))

In [83]:
X_data.shape

(159, 79)

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size = 0.2, random_state = 32)
print(f'X_train shape : {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape : (127, 79)
X_test shape: (32, 79)
y_train shape: (127,)
y_test shape: (32,)

In [85]:
poly_model = LinearRegression(X_train, y_train, learning_rate = 0.0000001, num_epochs = 100)
poly_model.fit()

Epoch: 0 - Loss : 4379089.079834225
Epoch: 1 - Loss : 137098.4489642925
Epoch: 2 - Loss : 61859.31250760842
Epoch: 3 - Loss : 59663.61486698118
Epoch: 4 - Loss : 58764.956595217096
Epoch: 5 - Loss : 57905.588636085464
Epoch: 6 - Loss : 57063.147836934455
Epoch: 7 - Loss : 56236.928521871305
Epoch: 8 - Loss : 55426.61064515449
Epoch: 9 - Loss : 54631.886865012464
Epoch: 10 - Loss : 53852.455892875376
Epoch: 11 - Loss : 53088.0222641455
Epoch: 12 - Loss : 52338.29622368953
Epoch: 13 - Loss : 51602.99361547579
Epoch: 14 - Loss : 50881.83577437805
Epoch: 15 - Loss : 50174.54942007087
Epoch: 16 - Loss : 49480.86655297518
Epoch: 17 - Loss : 48800.52435221456
Epoch: 18 - Loss : 48133.26507554352
Epoch: 19 - Loss : 47478.83596120926
Epoch: 20 - Loss : 46836.98913171024
Epoch: 21 - Loss : 46207.48149941408
Epoch: 22 - Loss : 45590.074673999545
Epoch: 23 - Loss : 44984.53487168695
Epoch: 24 - Loss : 44390.632826222674
Epoch: 25 - Loss : 43808.143701583795
Epoch: 26 - Loss : 43236.84700636938
Epoch: 27 - Loss : 42676.526509846386
Epoch: 28 - Loss : 42126.9701596176
Epoch: 29 - Loss : 41587.970000880734
Epoch: 30 - Loss : 41059.3220972475
Epoch: 31 - Loss : 40540.826453093076
Epoch: 32 - Loss : 40032.28693740575
Epoch: 33 - Loss : 39533.511209108256
Epoch: 34 - Loss : 39044.31064382225
Epoch: 35 - Loss : 38564.50026204766
Epoch: 36 - Loss : 38093.898658730264
Epoch: 37 - Loss : 37632.32793419002
Epoch: 38 - Loss : 37179.61362638411
Epoch: 39 - Loss : 36735.58464447933
Epoch: 40 - Loss : 36300.07320370735
Epoch: 41 - Loss : 35872.91476147951
Epoch: 42 - Loss : 35453.94795473583
Epoch: 43 - Loss : 35043.01453850468
Epoch: 44 - Loss : 34639.95932564969
Epoch: 45 - Loss : 34244.63012778106
Epoch: 46 - Loss : 33856.877697308475
Epoch: 47 - Loss : 33476.55567061421
Epoch: 48 - Loss : 33103.52051232384
Epoch: 49 - Loss : 32737.63146065414
Epoch: 50 - Loss : 32378.750473816945
Epoch: 51 - Loss : 32026.742177458927
Epoch: 52 - Loss : 31681.473813116558
Epoch: 53 - Loss : 31342.815187667613
Epoch: 54 - Loss : 31010.638623759223
Epoch: 55 - Loss : 30684.818911193786
Epoch: 56 - Loss : 30365.23325925441
Epoch: 57 - Loss : 30051.761249951676
Epoch: 58 - Loss : 29744.28479217344
Epoch: 59 - Loss : 29442.68807672126
Epoch: 60 - Loss : 29146.857532215145
Epoch: 61 - Loss : 28856.681781850646
Epoch: 62 - Loss : 28572.0516009916
Epoch: 63 - Loss : 28292.859875582068
Epoch: 64 - Loss : 28019.001561362296
Epoch: 65 - Loss : 27750.37364387245
Epoch: 66 - Loss : 27486.875099229343
Epoch: 67 - Loss : 27228.40685566121
Epoch: 68 - Loss : 26974.87175578565
Epoch: 69 - Loss : 26726.174519616405
Epoch: 70 - Loss : 26482.221708285288
Epoch: 71 - Loss : 26242.921688464765
Epoch: 72 - Loss : 26008.18459747842
Epoch: 73 - Loss : 25777.92230908525
Epoch: 74 - Loss : 25552.04839992541
Epoch: 75 - Loss : 25330.478116614177
Epoch: 76 - Loss : 25113.128343471803
Epoch: 77 - Loss : 24899.91757087714
Epoch: 78 - Loss : 24690.765864232468
Epoch: 79 - Loss : 24485.59483352834
Epoch: 80 - Loss : 24284.32760349636
Epoch: 81 - Loss : 24086.888784338767
Epoch: 82 - Loss : 23893.20444302369
Epoch: 83 - Loss : 23703.202075135
Epoch: 84 - Loss : 23516.810577266195
Epoch: 85 - Loss : 23333.9602199477
Epoch: 86 - Loss : 23154.58262109731
Epoch: 87 - Loss : 22978.61071998373
Epoch: 88 - Loss : 22805.978751693132
Epoch: 89 - Loss : 22636.62222208922
Epoch: 90 - Loss : 22470.477883257074
Epoch: 91 - Loss : 22307.483709421595
Epoch: 92 - Loss : 22147.578873331204
Epoch: 93 - Loss : 21990.70372309794
Epoch: 94 - Loss : 21836.799759485173
Epoch: 95 - Loss : 21685.809613633966
Epoch: 96 - Loss : 21537.677025220175
Epoch: 97 - Loss : 21392.346821033392
Epoch: 98 - Loss : 21249.764893969867
Epoch: 99 - Loss : 21109.878182431465

{'loss': np.float64(79526.51951232756),
 'weight': array([ 2.88556495e-01,  9.45043478e-01,  6.49177839e-01, -7.22352088e-01,
         5.87592722e-01, -3.75294540e-01, -2.31261705e-01, -1.20998407e+00,
        -7.47364841e-01, -1.17346505e+00, -1.81349935e+00,  2.26551911e-01,
        -1.49029841e-01,  2.23119571e-01, -1.14313257e+00, -3.61401181e-01,
        -1.73633467e+00, -1.29320133e+00,  1.70794409e+00,  4.70361703e-01,
        -6.85174921e-01, -9.82807447e-01, -4.01645884e-01, -3.03053969e-01,
         1.35341799e+00,  3.15216887e-01, -2.06144247e-01, -1.18427659e+00,
         1.17838143e+00, -1.10120206e+00, -1.89937512e+00, -5.15179552e-01,
         1.16675535e+00,  8.87127181e-02,  1.10625284e-01,  1.35195628e+00,
        -1.31207771e+00,  7.77937203e-01, -2.15120526e+00,  1.96139551e-03,
        -3.67405465e-01,  1.03566590e+00, -6.14782575e-01, -3.69542238e-01,
         1.12253609e+00, -1.72978135e+00,  1.61252056e+00, -7.56981974e-01,
        -1.19971649e-01,  6.95248323e-01,  6.42003423e-01,  5.17512222e-02,
         6.89982698e-01, -2.04042256e-01, -1.99380499e+00,  6.53465780e-01,
        -1.22511840e+00,  2.34576389e-01,  3.37415286e-01, -8.68679888e-01,
        -5.50672555e-01,  1.42877314e+00, -8.01265841e-01,  1.59879636e+00,
        -1.49087121e-01, -1.25516540e+00, -1.16673492e+00, -4.98647341e-02,
        -1.30980929e+00,  5.77040990e-01, -4.67377125e-02,  5.92750175e-01,
         1.23182917e+00, -2.10615111e-01, -1.79952692e+00, -1.17229514e+00,
        -2.44100882e-01,  2.89475076e-01, -1.71871814e-01])}

In [86]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

np.float64(0.8300384883024756)

In [87]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

np.float64(0.8541251707558094)